//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Candidate", Namespace="http://schemas.datacontract.org/2004/07/EternalBlue.Models")]
    public partial class Candidate : object
    {
        
        private string BarcodeField;
        
        private bool CanSwimField;
        
        private string CandidateIdField;
        
        private string DadField;
        
        private string EmailField;
        
        private ServiceReference1.Skill[] ExperienceField;
        
        private string FavoriteMusicGenreField;
        
        private string FirstNameField;
        
        private string FullNameField;
        
        private ServiceReference1.Gender GenderField;
        
        private string LastNameField;
        
        private string MomField;
        
        private string ProfilePictureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode
        {
            get
            {
                return this.BarcodeField;
            }
            set
            {
                this.BarcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanSwim
        {
            get
            {
                return this.CanSwimField;
            }
            set
            {
                this.CanSwimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CandidateId
        {
            get
            {
                return this.CandidateIdField;
            }
            set
            {
                this.CandidateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dad
        {
            get
            {
                return this.DadField;
            }
            set
            {
                this.DadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Skill[] Experience
        {
            get
            {
                return this.ExperienceField;
            }
            set
            {
                this.ExperienceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavoriteMusicGenre
        {
            get
            {
                return this.FavoriteMusicGenreField;
            }
            set
            {
                this.FavoriteMusicGenreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.Gender Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mom
        {
            get
            {
                return this.MomField;
            }
            set
            {
                this.MomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePicture
        {
            get
            {
                return this.ProfilePictureField;
            }
            set
            {
                this.ProfilePictureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skill", Namespace="http://schemas.datacontract.org/2004/07/EternalBlue.Models")]
    public partial class Skill : object
    {
        
        private string TechnologyIdField;
        
        private int YearsOfExperienceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnologyId
        {
            get
            {
                return this.TechnologyIdField;
            }
            set
            {
                this.TechnologyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearsOfExperience
        {
            get
            {
                return this.YearsOfExperienceField;
            }
            set
            {
                this.YearsOfExperienceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/Bogus.DataSets")]
    public enum Gender : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Technology", Namespace="http://schemas.datacontract.org/2004/07/EternalBlue.Models")]
    public partial class Technology : object
    {
        
        private string GuidField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRecruitmentService")]
    public interface IRecruitmentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecruitmentService/GetCandidates", ReplyAction="http://tempuri.org/IRecruitmentService/GetCandidatesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Candidate[]> GetCandidatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecruitmentService/GetTechnologies", ReplyAction="http://tempuri.org/IRecruitmentService/GetTechnologiesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Technology[]> GetTechnologiesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IRecruitmentServiceChannel : ServiceReference1.IRecruitmentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class RecruitmentServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IRecruitmentService>, ServiceReference1.IRecruitmentService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RecruitmentServiceClient() : 
                base(RecruitmentServiceClient.GetDefaultBinding(), RecruitmentServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecruitmentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RecruitmentServiceClient.GetBindingForEndpoint(endpointConfiguration), RecruitmentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecruitmentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecruitmentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecruitmentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecruitmentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecruitmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Candidate[]> GetCandidatesAsync()
        {
            return base.Channel.GetCandidatesAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Technology[]> GetTechnologiesAsync()
        {
            return base.Channel.GetTechnologiesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding))
            {
                return new System.ServiceModel.EndpointAddress("https://app.ifs.aero/EternalBlue/recruitment.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RecruitmentServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RecruitmentServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding,
        }
    }
}
